#line 1 "scanner.cpp"

#line 3 "scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 86
#define YY_END_OF_BUFFER 87
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[316] =
    {   0,
        0,    0,    0,    0,    0,    0,   87,   80,   77,   79,
       78,   39,   80,   80,   80,    9,   10,   21,   19,   17,
       20,   16,   22,    4,   15,   18,   25,   26,   24,   40,
       80,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   13,   14,   23,
       11,   80,   12,   86,   84,   86,   82,   86,   36,    0,
        8,   38,    0,    0,    0,   30,   27,   29,   28,   31,
        3,    2,   32,    0,    4,   34,   35,   33,    0,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,

       76,   76,   76,   76,   65,   76,   76,   76,   37,   85,
       83,   81,    6,    5,    0,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,    0,   76,   76,   69,
       76,   76,   76,   76,   76,   76,   76,   76,   51,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   62,   76,
       73,   76,   76,   76,   76,   76,   76,   67,   76,   76,
       76,    0,   76,   76,   50,   76,   76,   76,   76,   76,
       76,   76,    7,   72,   76,   76,   76,   76,   76,   76,

       76,   61,   76,   76,   76,   76,   76,   76,    0,   76,
       55,   76,    0,   76,   76,   76,   76,   76,   76,   76,
       76,   42,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,    0,   76,   76,    0,   76,
       76,   76,   76,   76,   44,   70,   63,   76,   76,   76,
        1,   76,   76,   76,   76,   53,   76,   52,   76,   76,
       66,   47,   76,    0,   41,   43,   76,   76,   76,   76,
       58,   45,   76,   71,   76,   76,   76,   57,   76,   76,
        0,   76,   64,   76,   56,   76,   76,   60,   54,   76,
        7,    0,   46,   76,   76,   74,   68,    0,   76,   76,

       76,    0,   76,   76,   75,   59,   76,   76,   76,   76,
       76,   76,   48,   49,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    1,    1,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   18,   19,   20,
       21,   22,   23,   24,   25,   26,   27,   28,   29,   30,
       31,   32,   33,   34,   34,   35,   36,   37,   38,   39,
       34,   40,   41,   42,   43,   44,   34,   34,   34,   34,
       45,   46,   47,   48,   49,    1,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   34,   34,   59,   60,   61,
       62,   63,   34,   64,   65,   66,   67,   68,   34,   34,
       34,   34,   69,   70,   71,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   34,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   34,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,   34,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[72] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    1,    1,    1,
        1,    1,    1,    1,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    3,    1,    1,    4,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    2,    2,
        2,    2,    2,    2,    2,    2,    2,    2,    1,    1,
        1
    } ;

static const flex_int16_t yy_base[322] =
    {   0,
        0,    0,  316,  295,   69,   70,  254, 1115, 1115, 1115,
     1115,  219,  233,  211,   57, 1115, 1115,  182,   63, 1115,
       62, 1115,   66,   71, 1115, 1115,  149,  148,  138, 1115,
       37,   62,   68,   72,   75,   77,   83,   98,   76,  111,
      118,  128,  132,  137,  156,  138,  173, 1115, 1115, 1115,
     1115,   88, 1115,   97, 1115,   90, 1115,   79, 1115,   99,
     1115, 1115,   82,  133,   74, 1115, 1115, 1115, 1115, 1115,
     1115, 1115, 1115,   84,  129, 1115, 1115, 1115,   81,  144,
      145,  151,  166,  167,  184,  175,  208,  200,  202,  194,
      203,  157,  209,  228,  230,  247,  224,  239,  253,  229,

      266,  254,  245,  273,  280,  274,  299,  278, 1115, 1115,
     1115, 1115, 1115,   79,  113,  264,  295,  289,  308,  304,
      316,  303,  318,  342,  345,  346,  332,  349,  359,  366,
      360,  370,  368,  369,  395,  372,  397,  406,  390,  414,
      410,  408,  416,  435,  444,  441,  173,  447,  454,  375,
      451,  458,  462,  469,  480,  465,  472,  470,  421,  487,
      482,  498,  495,  515,  520,  496,  513,  521,  507,  522,
      525,  540,  533,  537,  548,  555,  560,  586,  559,  576,
      577,  246,  582,  581,  526,  594,  584,  588,  599,  612,
      617,  601,  551,  593,  634,  623,  638,  645,  627,  624,

      650,  636,  663,  662,  660,  665,  664,  680,  244,  669,
      686,  691,  290,  687,  693,  709,  688,  703,  711,  713,
      716,  717,  722,  724,  744,  733,  747,  761,  750,  740,
      766,  764,  767,  770,  774,  408,  768,  792,  500,  795,
      791,  801,  809,  818,  807,  819,  820,  825,  826,  830,
      822,  837,  831,  844,  835,  828,  864,  846,  848,  865,
     1115,  866,  870,  300,  874,  882,  883,  888,  889,  887,
      890,  894,  905,  901,  907,  909,  908,  913,  928,  925,
      767,  931,  930,  934,  932,  944,  950,  949,  955,  965,
      956,  949,  959,  980,  968,  969,  971,  958,  994,  975,

      984,  316, 1009,  989,  993, 1115,  996, 1010, 1011, 1030,
     1024, 1018, 1034, 1035, 1115, 1094, 1098, 1102, 1105, 1107,
     1110
    } ;

static const flex_int16_t yy_def[322] =
    {   0,
      315,    1,  316,  316,  317,  317,  315,  315,  315,  315,
      315,  315,  318,  315,  319,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  318,
      315,  315,  315,  319,  319,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  321,
      320,  321,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  315,  315,
      315,  315,  315,  315,  315,  321,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  315,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  315,  320,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  320,  320,  321,  320,

      320,  320,  320,  320,  320,  320,  320,  320,  315,  320,
      320,  320,  315,  320,  320,  320,  320,  320,  320,  320,
      320,  320,  320,  320,  320,  320,  321,  320,  320,  320,
      320,  320,  320,  320,  320,  315,  320,  320,  315,  320,
      320,  320,  320,  320,  320,  320,  320,  321,  320,  320,
      320,  321,  320,  320,  320,  320,  320,  320,  320,  320,
      315,  320,  320,  315,  320,  320,  320,  320,  320,  321,
      320,  320,  321,  320,  320,  320,  320,  320,  320,  320,
      315,  320,  320,  320,  321,  321,  320,  320,  320,  320,
      320,  315,  320,  320,  321,  320,  320,  315,  320,  320,

      321,  315,  320,  320,  321,  315,  320,  320,  320,  320,
      320,  320,  320,  320,    0,  315,  315,  315,  315,  315,
      315
    } ;

static const flex_int16_t yy_nxt[1187] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       32,   38,   39,   32,   40,   41,   42,   32,   43,   44,
       45,   46,   32,   47,   48,    8,   49,   50,    8,   32,
       33,   34,   35,   36,   37,   32,   38,   39,   40,   41,
       42,   32,   43,   44,   45,   46,   32,   47,   51,   52,
       53,   57,   57,   63,   67,   69,   71,   79,   80,   58,
       58,   72,   70,   68,   80,   74,   73,   75,   80,  113,
       63,   80,   80,   80,  112,  114,   84,  111,   63,   80,

      114,   79,   65,   87,   61,   83,   85,   90,  111,   86,
       82,   93,   94,   88,   80,  110,   82,   89,  115,  315,
       82,   84,   91,   82,   82,   82,   92,   80,   87,   83,
       85,   82,   90,   86,   80,   93,   94,   88,  147,   95,
      113,   89,  115,   74,   80,   75,   82,   91,   80,  315,
       96,   92,   98,   80,   80,   97,  100,  109,   78,   82,
       80,   80,  106,  147,   95,  103,   82,   80,   77,   76,
       99,  101,   80,   80,  102,   96,   82,   98,  315,   97,
       82,  100,   80,   80,  104,   82,   82,  106,  105,   80,
      103,   80,   82,   82,   99,  101,  129,  107,  102,   82,

       80,  108,   66,  117,   82,   82,  118,  119,  120,  104,
       80,  121,  182,  105,   82,   82,   80,   62,   80,   80,
      129,   82,  107,   82,   80,   80,  108,  117,  127,  128,
      118,  119,   82,  120,  122,  121,  182,  123,   61,   59,
       80,  125,   82,  126,   80,   80,   80,  130,   82,  124,
       82,   82,  127,  315,  128,   80,   82,   82,  132,  122,
      131,   80,  123,   80,  134,  125,  135,  126,  137,   80,
       80,  130,   82,  124,  213,  133,   82,   82,   82,  140,
       80,  136,   80,  132,  236,  131,  141,   82,  134,   80,
       80,  135,  137,   82,   80,   82,   80,   55,  138,  213,

      133,   82,   82,  139,  140,   80,  136,  142,  236,  144,
      141,   80,   82,  149,   82,   80,  143,  146,   55,   80,
       80,   82,   82,  138,   80,  145,   82,  139,   82,  148,
      239,  142,   80,  144,   80,  155,  315,   82,  149,  281,
      143,  146,  152,   82,  151,  150,  156,   82,   80,  315,
      145,   82,   82,  148,  239,  306,   82,  153,   80,  154,
      155,   80,   80,  281,   82,   80,   82,  152,  151,  150,
      157,  156,  160,  158,  159,   80,   80,  161,  315,  306,
       82,  153,   80,  154,   80,   80,   80,  162,   80,  315,
       82,   80,  315,   82,   82,  157,  160,   82,  158,  159,

      315,  165,  161,  163,  167,  164,   80,   82,   82,  166,
      168,   80,  162,   80,   82,  170,   82,   82,   82,  169,
       82,  171,   80,   82,   80,  165,   80,  163,  167,  164,
       80,  174,   80,  166,  168,  315,  177,   80,   82,  170,
      261,  315,  172,   82,  169,   82,  171,  176,  175,  173,
      315,   80,  315,  178,   82,  174,   82,   80,   82,  179,
       80,  177,   82,   80,   82,  261,  172,   80,  181,   82,
       80,  176,  175,  173,   80,  183,  180,  178,   80,  185,
      184,   80,  186,   82,  179,   80,   80,  315,   80,   82,
      315,  190,   82,  181,  187,   82,   80,  188,   80,   82,

      183,  180,   82,   80,  185,  184,   82,  186,  191,  192,
       82,   80,   80,   82,   80,  189,  190,   82,   82,  187,
       82,  194,  188,   80,  193,  195,  264,  315,   82,   80,
       82,   80,  191,  192,  196,   82,   80,   80,   80,  189,
      315,   80,   80,   82,  199,  194,   82,  197,  193,   80,
      195,  264,  198,   80,  200,   82,   80,  204,  196,  202,
      201,   82,  315,   82,   80,  205,  203,   80,   82,   82,
       82,   80,  197,   82,   82,   80,   80,  198,  200,  315,
      206,   82,  204,  202,  201,   82,  208,  209,   82,  209,
      205,  203,   80,   80,  207,  210,   82,   80,   80,   82,

       80,  212,   80,   82,   80,  206,  214,   82,   82,   80,
       80,  208,  315,  211,  315,   80,  315,   80,  207,  210,
      217,  315,  215,  219,   82,   82,  212,  218,   80,   82,
       82,  214,   82,   80,   82,  216,   82,  211,  222,   80,
       80,   82,   82,   80,  217,  221,  215,   82,  219,   82,
       80,  218,   80,  220,   80,  315,  315,  315,  223,  216,
       82,   80,  222,  228,  224,   82,   80,  315,  227,  226,
      221,   82,   82,  225,  229,   82,   80,  220,   80,   80,
       80,   80,   82,  223,   82,   80,   82,  228,  224,  231,
      232,  233,  227,   82,  226,  230,   80,  225,   82,  229,

      234,  237,   80,   80,   80,  315,  235,   80,   82,   80,
       82,   82,   82,   82,  231,  232,  233,   82,  238,   80,
      230,  241,  315,  240,  234,   80,  237,   80,   82,   80,
      243,  235,   80,   80,   82,   82,   82,  242,   80,   82,
       80,   82,  315,  238,  244,  245,  241,  240,  249,   80,
      246,   82,  315,  315,  243,  247,   80,   82,  315,   82,
       80,   82,  242,   80,   82,   82,   80,  251,  244,  245,
      248,  315,   82,  249,  246,  252,  250,   80,  255,  247,
       80,   82,   80,   80,   80,  253,   80,  315,   82,  254,
       80,  251,   82,  315,  259,   82,  257,  315,   82,  292,

      252,  250,  255,  256,  258,  262,  260,   80,   80,   82,
      253,   80,   82,  254,   82,   82,   82,   80,   82,  259,
      263,  257,   82,   80,  292,   80,  315,  256,  258,  262,
      266,  260,  265,  268,   80,   80,   80,  267,   80,   82,
       82,   80,   80,   82,   80,  263,   80,   80,  315,   82,
      269,   80,  270,   80,  266,   82,  265,   82,  268,  276,
       80,  267,   80,  273,   80,  271,   82,   82,   82,  272,
       82,  274,  275,   82,   82,  269,   82,  270,   82,   82,
       80,   80,   80,   82,  276,   82,   80,  278,  273,  271,
       80,  277,   82,  272,   82,  274,   82,  275,   80,   80,

      315,  315,  279,   80,   80,   80,   80,  282,  315,  280,
       80,  278,   82,   82,   82,  285,  277,   80,   82,  315,
      315,   80,   82,   80,   80,   80,  279,  283,  284,   80,
       82,   82,  282,  280,  287,   82,   82,   82,   82,  286,
      285,   80,   82,  288,   80,  289,   80,   80,   80,   82,
       80,  283,  284,   82,  315,   82,   82,   82,  294,  287,
       80,   82,  291,  286,  290,   80,   80,  288,  295,  289,
      293,   80,   80,   82,  298,   80,   82,  296,   82,   82,
       82,   80,   82,  294,   80,   80,  291,   80,  290,  297,
      302,   80,   82,  295,  293,  301,   80,   82,   82,  298,

       80,  315,  296,   82,   82,   80,  299,   82,  300,   80,
       80,  304,   80,   82,  297,  302,   82,   82,  303,   82,
      301,  305,  315,   82,  309,   80,   80,   80,   82,  315,
      308,  299,   82,  300,   80,  304,  307,   82,  310,  315,
       80,   82,   82,  303,   82,  305,   80,  311,  313,  309,
       80,   80,  315,  315,  308,  314,  315,   82,   82,   82,
      315,  307,  315,  310,  315,  315,   82,  315,  315,  312,
      315,  311,   82,  313,  315,  315,  315,  315,   82,  314,
      315,  315,   82,   82,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  312,   54,   54,   54,   54,   56,   56,

       56,   56,   60,   60,   60,   60,   64,   64,   81,  315,
       81,  116,  315,  116,    7,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315
    } ;

static const flex_int16_t yy_chk[1187] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,   15,   19,   21,   23,   31,   32,    5,
        6,   23,   21,   19,   33,   24,   23,   24,   34,   63,
       65,   35,   39,   36,   58,  114,   34,   58,   63,   37,

       74,   31,   15,   35,   60,   33,   34,   37,   56,   34,
       32,   39,   39,   36,   38,   54,   33,   36,   79,   65,
       34,   34,   38,   35,   39,   36,   38,   40,   35,   33,
       34,   37,   37,   34,   41,   39,   39,   36,  115,   40,
       64,   36,   79,   75,   42,   75,   38,   38,   43,   64,
       41,   38,   42,   44,   46,   41,   43,   52,   29,   40,
       80,   81,   46,  115,   40,   44,   41,   82,   28,   27,
       42,   43,   45,   92,   43,   41,   42,   42,   64,   41,
       43,   43,   83,   84,   45,   44,   46,   46,   45,   47,
       44,   86,   80,   81,   42,   43,   92,   47,   43,   82,

       85,   47,   18,   83,   45,   92,   84,   84,   85,   45,
       90,   86,  147,   45,   83,   84,   88,   14,   89,   91,
       92,   47,   47,   86,   87,   93,   47,   83,   90,   91,
       84,   84,   85,   85,   87,   86,  147,   87,   13,   12,
       97,   88,   90,   89,   94,  100,   95,   93,   88,   87,
       89,   91,   90,    7,   91,   98,   87,   93,   95,   87,
       94,  103,   87,   96,   97,   88,   98,   89,  100,   99,
      102,   93,   97,   87,  182,   96,   94,  100,   95,  102,
      116,   99,  101,   95,  209,   94,  103,   98,   97,  104,
      106,   98,  100,  103,  108,   96,  105,    4,  101,  182,

       96,   99,  102,  101,  102,  118,   99,  104,  209,  106,
      103,  117,  116,  118,  101,  107,  105,  108,    3,  122,
      120,  104,  106,  101,  119,  107,  108,  101,  105,  117,
      213,  104,  121,  106,  123,  122,    0,  118,  118,  264,
      105,  108,  121,  117,  120,  119,  123,  107,  127,    0,
      107,  122,  120,  117,  213,  302,  119,  121,  124,  121,
      122,  125,  126,  264,  121,  128,  123,  121,  120,  119,
      124,  123,  127,  125,  126,  129,  131,  128,    0,  302,
      127,  121,  130,  121,  133,  134,  132,  129,  136,    0,
      124,  150,    0,  125,  126,  124,  127,  128,  125,  126,

        0,  131,  128,  130,  133,  130,  139,  129,  131,  132,
      134,  135,  129,  137,  130,  136,  133,  134,  132,  135,
      136,  137,  138,  150,  142,  131,  141,  130,  133,  130,
      140,  139,  143,  132,  134,    0,  142,  159,  139,  136,
      236,    0,  138,  135,  135,  137,  137,  141,  140,  138,
        0,  144,    0,  143,  138,  139,  142,  146,  141,  144,
      145,  142,  140,  148,  143,  236,  138,  151,  146,  159,
      149,  141,  140,  138,  152,  148,  145,  143,  153,  151,
      149,  156,  152,  144,  144,  154,  158,    0,  157,  146,
        0,  156,  145,  146,  153,  148,  155,  154,  161,  151,

      148,  145,  149,  160,  151,  149,  152,  152,  157,  158,
      153,  163,  166,  156,  162,  155,  156,  154,  158,  153,
      157,  161,  154,  169,  160,  162,  239,    0,  155,  167,
      161,  164,  157,  158,  163,  160,  165,  168,  170,  155,
        0,  171,  185,  163,  166,  161,  162,  164,  160,  173,
      162,  239,  165,  174,  167,  169,  172,  173,  163,  170,
      168,  167,    0,  164,  175,  174,  172,  193,  165,  168,
      170,  176,  164,  171,  185,  179,  177,  165,  167,    0,
      175,  173,  173,  170,  168,  174,  177,  178,  172,  178,
      174,  172,  180,  181,  176,  179,  175,  184,  183,  193,

      187,  181,  178,  176,  188,  175,  183,  179,  177,  194,
      186,  177,    0,  180,    0,  189,    0,  192,  176,  179,
      187,    0,  184,  189,  180,  181,  181,  188,  190,  184,
      183,  183,  187,  191,  178,  186,  188,  180,  192,  196,
      200,  194,  186,  199,  187,  191,  184,  189,  189,  192,
      195,  188,  202,  190,  197,    0,    0,    0,  195,  186,
      190,  198,  192,  200,  196,  191,  201,    0,  199,  198,
      191,  196,  200,  197,  201,  199,  205,  190,  204,  203,
      207,  206,  195,  195,  202,  210,  197,  200,  196,  204,
      205,  206,  199,  198,  198,  203,  208,  197,  201,  201,

      207,  210,  211,  214,  217,    0,  208,  212,  205,  215,
      204,  203,  207,  206,  204,  205,  206,  210,  212,  218,
      203,  215,    0,  214,  207,  216,  210,  219,  208,  220,
      217,  208,  221,  222,  211,  214,  217,  216,  223,  212,
      224,  215,    0,  212,  218,  219,  215,  214,  224,  226,
      220,  218,    0,    0,  217,  221,  230,  216,    0,  219,
      225,  220,  216,  227,  221,  222,  229,  226,  218,  219,
      223,    0,  224,  224,  220,  227,  225,  228,  230,  221,
      232,  226,  231,  233,  237,  228,  234,    0,  230,  229,
      235,  226,  225,    0,  234,  227,  232,    0,  229,  281,

      227,  225,  230,  231,  233,  237,  235,  241,  238,  228,
      228,  240,  232,  229,  231,  233,  237,  242,  234,  234,
      238,  232,  235,  245,  281,  243,    0,  231,  233,  237,
      241,  235,  240,  243,  244,  246,  247,  242,  251,  241,
      238,  248,  249,  240,  256,  238,  250,  253,    0,  242,
      244,  255,  248,  252,  241,  245,  240,  243,  243,  255,
      254,  242,  258,  252,  259,  249,  244,  246,  247,  250,
      251,  253,  254,  248,  249,  244,  256,  248,  250,  253,
      257,  260,  262,  255,  255,  252,  263,  259,  252,  249,
      265,  257,  254,  250,  258,  253,  259,  254,  266,  267,

        0,    0,  260,  270,  268,  269,  271,  267,    0,  263,
      272,  259,  257,  260,  262,  270,  257,  274,  263,    0,
        0,  273,  265,  275,  277,  276,  260,  268,  269,  278,
      266,  267,  267,  263,  275,  270,  268,  269,  271,  273,
      270,  280,  272,  276,  279,  277,  283,  282,  285,  274,
      284,  268,  269,  273,    0,  275,  277,  276,  284,  275,
      286,  278,  280,  273,  279,  288,  287,  276,  286,  277,
      282,  289,  291,  280,  292,  293,  279,  287,  283,  282,
      285,  290,  284,  284,  295,  296,  280,  297,  279,  290,
      298,  300,  286,  286,  282,  295,  294,  288,  287,  292,

      301,    0,  287,  289,  291,  304,  294,  293,  294,  305,
      299,  300,  307,  290,  290,  298,  295,  296,  299,  297,
      295,  301,    0,  300,  307,  303,  308,  309,  294,    0,
      304,  294,  301,  294,  312,  300,  303,  304,  308,    0,
      311,  305,  299,  299,  307,  301,  310,  309,  311,  307,
      313,  314,    0,    0,  304,  312,    0,  303,  308,  309,
        0,  303,    0,  308,    0,    0,  312,    0,    0,  310,
        0,  309,  311,  311,    0,    0,    0,    0,  310,  312,
        0,    0,  313,  314,    0,    0,    0,    0,    0,    0,
        0,    0,    0,  310,  316,  316,  316,  316,  317,  317,

      317,  317,  318,  318,  318,  318,  319,  319,  320,    0,
      320,  321,    0,  321,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  315,  315,  315,  315,  315
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[87] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    0, 0, 1, 0, 1, 0, 0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "lexico.l"
#line 4 "lexico.l"
#include <cstdlib>
#include "parser.h"
#include <QString>
#include <stdio.h>
#include <iostream>
#include <nodo.h>

int yylex();
void yyerror(const char *s);
int linea=0; // Para contar lineas
int columna = 1; // para las columnas
nodo *raiz;
#line 854 "scanner.cpp"

#line 856 "scanner.cpp"

#define INITIAL 0
#define COM 1
#define COMM 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif
    
#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 34 "lexico.l"

#line 1075 "scanner.cpp"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 316 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1115 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 35 "lexico.l"

	YY_BREAK

case 2:
YY_RULE_SETUP
#line 37 "lexico.l"
{  BEGIN COM; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 38 "lexico.l"
{  BEGIN COMM; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 39 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return entero;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 40 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return decimal;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 41 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return caracter;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 42 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return booleano;}
	YY_BREAK
case 8:
/* rule 8 can match eol */
YY_RULE_SETUP
#line 43 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return cadena;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 44 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return parA; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 45 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return parC; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 46 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return illave; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 47 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return fllave; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 48 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return iCor; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 49 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return fCor; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 50 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return dosP; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 51 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return punto; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 52 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return coma; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 53 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return puntoComa; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 54 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return suma; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 55 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return menos; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 56 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return multi; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 57 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return division; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 58 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return potencia; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 59 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return mayor; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 60 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return menor; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 61 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return igual; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 62 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return aumento;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 63 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return decremento;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 64 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return masigual; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 65 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return porigual; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 66 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return menosigual; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 67 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return divigual; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 68 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return mayorigual; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 69 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return menorigual; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 70 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return igualigual; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 71 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return desigual; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 72 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return o; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 73 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return y; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 74 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return no; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 75 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return interrogacion; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 76 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return tipoBooleano;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 77 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return tipoEntero; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 78 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return tipoCaracter; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 79 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return tipoDecimal; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 80 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return imprimir; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 81 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return concatenar; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 82 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return tamanio; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 83 "lexico.l"
{ strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return convertirAcadena;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 84 "lexico.l"
{ strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return convertirAentero;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 85 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return clase;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 86 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return este;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 87 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return publico;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 88 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return privado;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 89 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return protegido;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 90 "lexico.l"
{ strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return vacio;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 91 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return heredade;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 92 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return retornar;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 93 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return importar;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 94 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return sobreescribir;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 95 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return principal;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 96 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return nuevo;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 97 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return nada; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 98 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return detener;}// Sentencias de flujo de control
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 99 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return continuar;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 100 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return si; }// IF
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 101 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return sinosi; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 102 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return sino; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 103 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return selecciona;}// Switch case
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return caso; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return defecto; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return mientras;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return hacer; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return para; }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return mostraredd; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 110 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return leer_teclado; }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 111 "lexico.l"
{  strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext); return id; }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 112 "lexico.l"
{
                    strcpy(yylval.TEXT, yytext); columna=26;
                }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 115 "lexico.l"
{ columna++; }
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 116 "lexico.l"
{linea++; columna = 0;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 117 "lexico.l"
{
                    strcpy(yylval.TEXT, yytext); columna=columna+strlen(yytext);
                    std::cout <<yytext <<" Error Lexico en la linea "<< linea << " Columna:"<< columna<<  std::endl;
                }
	YY_BREAK

case 81:
YY_RULE_SETUP
#line 122 "lexico.l"
{ BEGIN INITIAL; }
	YY_BREAK
case 82:
/* rule 82 can match eol */
YY_RULE_SETUP
#line 123 "lexico.l"
{linea++;};
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 124 "lexico.l"

	YY_BREAK
case YY_STATE_EOF(COMM):
#line 125 "lexico.l"
{ yyerror("unclosed comment"); }
	YY_BREAK
case 84:
/* rule 84 can match eol */
YY_RULE_SETUP
#line 126 "lexico.l"
{ linea++; columna = 0; BEGIN INITIAL; };
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 127 "lexico.l"

	YY_BREAK
case 86:
YY_RULE_SETUP
#line 128 "lexico.l"
ECHO;
	YY_BREAK
#line 1587 "scanner.cpp"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(COM):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 316 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 316 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 315);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 128 "lexico.l"


